language: node_js

node_js:
  - "lts/*"

branches:
  only:
    - master
    - develop
    - /feature\/*/

notifications:
 email: false
 slack:
   rooms:
     - edu-connect:Rurv5WxxeDgRZ8oi9JWHogQQ#fe_github

install:
  - yarn

script:
  - eslint src/.
  - yarn test
  - yarn build
  - if [[ "$TRAVIS_BRANCH" == "develop" ]] && [[ "$TRAVIS_PULL_REQUEST" == false ]]; then curl -X GET http://ec2-13-125-21-21.ap-northeast-2.compute.amazonaws.com:9999/deploy/FE_develop ; elif [[ "$TRAVIS_BRANCH" == "master" ]] && [[ "$TRAVIS_PULL_REQUEST" == false ]]; then curl -X GET http://ec2-13-125-21-21.ap-northeast-2.compute.amazonaws.com:9999/deploy/FE_master ; fi
